INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'SYSTEM', 'MAX_LOGIN', '5', 'Số lần đăng nhập tối đa', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'SYSTEM', 'SESSION_TO', '30', 'Thời gian timeout session (phút)', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'EMAIL', 'SMTP_HOST', 'smtp.gmail.com', 'SMTP server host', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'EMAIL', 'SMTP_PORT', '587', 'SMTP server port', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'EMAIL', 'FROM_ADDR', 'noreply@gms.com', 'Email địa chỉ gửi mặc định', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'SECURITY', 'PWD_MIN', '8', 'Độ dài mật khẩu tối thiểu', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'SECURITY', 'PWD_EXP', '90', 'Thời gian hết hạn mật khẩu (ngày)', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'BACKUP', 'BACKUP_PATH', '/backup/data', 'Đường dẫn lưu backup', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'BACKUP', 'BACKUP_FREQ', 'DAILY', 'Tần suất backup (DAILY/WEEKLY/MONTHLY)', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

INSERT INTO SYS_PARAMETERS (ID, PARA_DOMAIN, PARA_CD, PARA_VALUE, DESCRIPTION, ACTIVE_FLG, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())), 'NOTIFICATION', 'ENABLE_EMAIL', '1', 'Bật/tắt thông báo email (1/0)', 1, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE);

